### ISSUE TITLE
(log ∘ exp) gives strange output

### ISSUE THREAD

**Issue by alok** [chakravala/Grassmann.jl#103]
```
In [3]: using Grassmann
@
In [4]: @basis 3
(⟨×××⟩, v, v₁, v₂, v₃, v₁₂, v₁₃, v₂₃, v₁₂₃)

In [5]: log(exp(v2))
0.8302832053942902 + 0.7252492942757254v₂

In [6]: exp(log(v2))
17807.1620787955 + 17807.16205071691v₂

In [7]: (log ∘ exp)
log ∘ exp

In [8]: typeof(log ∘ exp)
ComposedFunction{typeof(log), typeof(exp)}

In [9]: (log ∘ exp)(v2)
0.8302832053942902 + 0.7252492942757254v₂

In [10]: (exp ∘log)(v2)
17807.1620787955 + 17807.16205071691v₂
```

Shouldn't this act as the identity? It does work (upto float precision) with `v12`.

**Comment by chakravala** [comment]
Thanks for opening this issue, I already figured out what the problem is immediately after you posted it.

First of all, `v12` is like an imaginary unit, so the behavior is well defined. Second, `v2` is not an imaginary unit and it involves hyperbolic geometry, which is uncommon and the `log` method you are calling is a new experimental method I recently added based on my own ideas. Previously, it was not possible to calculate this with `Grassmann` and this is new.

For `log(exp(v2))` I get
```Julia
julia> log(exp(v2))
0.9999999999999999v₂
```
So that is correct. However, indeed the opposite `exp(log(v2))` is
```Julia
julia> exp(log(v2))
17807.1620787955 + 17807.16205071691v₂
```
That is strange indeed.

The reason this is wrong is because when you call `log` on the number `v2` it doesn't call the new method which I implemented recently. In order to get it to call the new method, you can try this instead:
```Julia
julia> log(0v+v2)
ERROR: DomainError with -1.0:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
Stacktrace:
 [1] sqrt
   @ ./math.jl:677 [inlined]
 [2] sqrt
   @ ./math.jl:1491 [inlined]
 [3] radius
   @ ~/.julia/dev/Grassmann/src/multivectors.jl:588 [inlined]
 [4] log(t::GaussianInteger{⟨×××⟩, v₂, Int64})
   @ Grassmann ~/.julia/dev/Grassmann/src/composite.jl:289
 [5] top-level scope
   @ REPL[37]:1
```
The new method I implemented will tell you that this is not a valid computation, as it is outside the geometry in question. You simply cannot ask for this computation because it is invalid.

In order to fix this, I simply need to fix up some of the dispatch in a commit really quick:
```Julia
Base.log(t::TensorTerm) = log(Couple(t))
```

**Comment by chakravala** [comment]
Now you will receive the correct error message for `log(v2)` which is an invalid computation:
```Julia
julia> using Grassmann; basis"3"
(⟨×××⟩, v, v₁, v₂, v₃, v₁₂, v₁₃, v₂₃, v₁₂₃)

julia> log(v2)
ERROR: DomainError with -1.0:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
Stacktrace:
 [1] sqrt
   @ ./math.jl:677 [inlined]
 [2] sqrt
   @ ./math.jl:1491 [inlined]
 [3] radius
   @ ~/.julia/dev/Grassmann/src/multivectors.jl:588 [inlined]
 [4] log(t::GaussianInteger{⟨×××⟩, v₂, Int64})
   @ Grassmann ~/.julia/dev/Grassmann/src/composite.jl:290
 [5] log(t::Submanifold{⟨×××⟩, 1, 0x0000000000000002})
   @ Grassmann ~/.julia/dev/Grassmann/src/composite.jl:287
 [6] top-level scope
   @ REPL[20]:1
```

**Comment by alok** [comment]
How would I interpret it with the hyperbolic stuff you alluded to? If I _did_ want that, then what would I do?

**Comment by chakravala** [comment]
Note that you can make the computation evaluate by using `Complex(1)` as a coefficient:
```Julia
julia> log(Complex(1)*v2)
0.0v₂

julia> exp(log(Complex(1)*v2))
v
```
However, julia does not allow this unless you are using a `Complex` field algebra. Technically, you can still do the computation with `sqrt(-1)` but Julia does not allow this unless you specifically want to work with `Complex` coefficients due to the Julia language design.

However, my algorithm was not designed for having `Complex` coefficients for this particular computation, I don't think it is meaningful even if it somehow evaluates.

**Comment by chakravala** [comment]
Additionally, note that `exp(log(Complex(1)*v2))` does not return `v2` again because when you apply `exp` to any value of zero you will get back a one.

**Comment by chakravala** [comment]
So, I really wouldn't use this with `Complex` coefficients personally, as I am not aware of any geometrical meaning for that and it doesn't really make any sense to me. When it returns an error, for `Real` coefficients, I would just accept that it's not a meaningful computation.

I don't believe my algorithm design is intended to support `Complex` values in this case, even if you somehow force it.

**Comment by chakravala** [comment]
If you want a better intuition for why I call this an invalid computation, it's because you are basically asking for something `x` for which `exp(x) == v2` ... this  is impossible, no such number really exists in the hyperbolic plane geometry, which is fundamentally different from a complex plane. Hyperbolic geometry is fundamentally different and it's not as nice as complex geometry, in the sense that you will only encounter this type of computation being invalid within the context of hyperbolic geometry but not in complex geometry. You cannot use the exponential function to obtain a value like `v2` in the hyperbolic plane, but you can do it in the complex plane with `exp(π/2*im)` and this will give you `im` the complex unit. If you compare hyperbolic geometry with complex geometry, then you will understand that this concept cannot exist in one of the two geometries.

**Comment by Jollywatt** [comment]
Just a note — there is actually a real solution to $\log(v_2)$ in the 3D Euclidean geometric algebra: $\frac{\pi I}{2}(1 - v_2)$ where $I$ is the pseudoscalar.

```
julia> π*I/2*(1 - v2)
8-component Multivector{3, 0:3, MVector{8, Float64}}:
 1.5708 v13
 1.5708 v123

julia> exp(ans) ≈ v2
true
```

Indeed, it's difficult to write a general algorithm that finds real logarithms, though, because of course there may be zero, some or infinitely many. But if you can find a complex solution, and the algebra has a commuting pseudoscalar squaring to $-1$, then you can replace the imaginary $i$ with $I$ to get a real multivector solution.

**Comment by chakravala** [comment]
Note that the number from @Jollywatt is not a hyperbolic number, like we are discussing here in this issue:
```julia
julia> exp(π/2*(v13+I))
-2.0839045713483273e-6 + 1.0000020839045713v₂ - 3.863929447642745e-7v₁₃ - 3.863929447642745e-7v₁₂₃
```
As I said, there is no hyperbolic number which `exp` to `v2` as this is impossible due to the nature of hyperbolic geometry.

The solution which @Jollywatt is proposing is outside of the scope of hyperbolic geometry.
