### ISSUE TITLE
norm, left contraction

### ISSUE THREAD

**Issue by Orbots** [chakravala/Grassmann.jl#26]
couple of nice to haves.

norm( Multivector/Blade).  Here's a discussion:  https://math.stackexchange.com/questions/958559/norm-on-a-geometric-algebra
The implementation for euclidean norm is to sum squares of each coefficient for each basis vector in M.  Then square root of the whole thing.  Basically the same thing you do for a norm of a "normal" gibbs vector. 

access to left contraction inner product.  I understand there are 4? different choices for \cdot and you've chosen the right contraction.  Which is cool, no complaints.  I'm more partial to a left contraction.  How do get that?

**Comment by chakravala** [comment]
The norm you want is already exported under the name `frobenius(x) = norm(value(x))`.

The left contraction is accessible with the `⨼` or `<` operators, but is not as optimized as the right version.

The other norm you mention can be obtained like this `⊛(a,b) = scalar(a*conj(b))`.

Haven't had much time to document so much new functionality yet. With this package, the functionality can grow very fast with a few lines of code... more than I can write about quickly.

**Comment by Orbots** [comment]
Thanks.  Still, would be nice if LinearAlgebra.norm(x) == frobenius(x), then you don't need to document it :)
Ok, time to look up ⨼ in the unicode table.

**Comment by chakravala** [comment]
> would be nice if LinearAlgebra.norm(x) == frobenius(x), then you don't need to document it :)

@Orbots so you want the Euclidean / Frobenius norm defined for `norm` or the *scalar product norm* which can become negative? what should be the name for the norm based on scalar product? should there be such a norm or should it not have its own function also?

I think I will move this issue to [AbstractTensors.jl](https://github.com/chakravala/AbstractTensors.jl) since this issue can be handled on a very abstract scope for all `TensorAlgebra` in the future.
