### ISSUE TITLE
Naive question on visualization workflow

### ISSUE THREAD

**Issue by goballooning** [chakravala/Grassmann.jl#28]
Thanks for making such a great GA lib available.

How do you visualize the results? 
I'm trying to analyze geometric structure in GA.
Can you recommend a workflow or any libraries (if you are already aware of by change) ?

Thanks!
Best,
Hongying

P.S. Previously I use "gable" by Leo Dorst, and also noticed GAlgebra (in Python) and its Julia wrapper).

**Comment by chakravala** [comment]
> How do you visualize the results?

Personally, I have not needed to use visualization yet, since I am relying on pure abstract reasoning and working with formulas in arbitrary number of dimensions.

However, I do plan on making my visualization code available at [ProjectiveGeometry.jl](https://github.com/chakravala/ProjectiveGeometry.jl) once I have more time available to focus on those aspects.

>  Can you recommend a workflow or any libraries (if you are already aware of by change) ?

Probably have a look at [ganja.js](https://github.com/enkimute/ganja.js)

> P.S. Previously I use "gable" by Leo Dorst, and also noticed GAlgebra (in Python) and its Julia wrapper).

This `Grassmann` is the first library I am using for geometric algebra, I do not have much experience with the other libraries, although I study their code and discuss with their authors frequently.

**Comment by goballooning** [comment]
Thank you! 

"ganja.js" seems promising. 
And I'm also following your "ProjectiveGeometry.jl" :).

Cheers,
Hongying

**Comment by chakravala** [comment]
There has been some progress on the Visualization aspect as I just [mentioned](https://discourse.julialang.org/t/ann-grassmann-jl-differential-geometric-algebra/21125/18?u=chakravala) on discourse.

**Comment by chakravala** [comment]
Based on the [ganja.js](https://github.com/enkimute/ganja.js) form @enkimute there is a new visualization option under way: [Ganja.jl](https://github.com/chakravala/Ganja.jl)

**Comment by chakravala** [comment]
I am creating a new visualization tool at https://github.com/chakravala/Ajna.jl beginning stages for now
