### ISSUE TITLE
Review comments for JuliaCon2019

### ISSUE THREAD

**Issue by snoeyink** [chakravala/Grassmann.jl#29]
Please see comments in the pdf of your JuliaCon submission. 
[grassmann-juliacon-2019.pdf](https://github.com/chakravala/Grassmann.jl/files/3363482/grassmann-juliacon-2019.pdf)
[Summary of Comments on grassmann-juliacon-2019.pdf](https://github.com/chakravala/Grassmann.jl/files/3363483/Summary.of.Comments.on.grassmann-juliacon-2019.pdf)

This paper is a description of Grassmann.jl and its supporting packages, which are appear quite impressive and extensive. Unfortunately, it
assumes extensive knowledge of terminology and notation from the reader, without ever defining what that reader should know, whose
notations they should be familiar with, and what that reader can expect to gain from reading.

As someone who has written a lot of geometric and topological code in low dimensions, and been interested in Clifford algebra enough
to read the book of Dorst, Fontijne, & Mann and some of Hestenes, I was eager to review this. I was disappointed because it does not
clearly say what the package does, nor what decisions were made between alternative implementations. (There are many intriguing hints,
e.g., Due to the design of the VectorBundle type
system, these operations make code optimization easier at compile-time by evaluating the bit parameters.)

As Fred Brooks has said, "Since anyone can create something new [in a synthetic field], that alone does not establish a contribution.
Rather, one must show that the creation is better." (Quoted from https://cra.org/resources/best-practice-memos/evaluating-computerscientists-and-engineers-for-promotion-and-tenure/) A paper should do more than quote from the documentation of a package; it
should provide context so the reader (from the author's desired audience) can understand the decisions made by the package author and
why they are better than alternatives.

**Comment by chakravala** [comment]
Thanks for your helpful comments, since I am not affiliated with a university, it is only through comments like yours that I will be able to improve and refine the presentation of the information.

From the submission website, I was under the impression that the paper has to be limited to 6 pages, so I had to leave out information that I would otherwise like to explain.. which is why I also want to write a much more detailed paper based on this one.

At the moment, I'm not sure whether the short version of the paper can really address the concerns you are having. To address those concerns, a much longer paper would have to be written, which would take more time and be more than 6 pages.

Certainly, I would like to address all those concerns; however, with the limited publication space for JuliaCon, it is difficult to cover. You will not be able to find some of the notation in any references, since some of it is original or modified to suit my own needs.. although it is all based in existing concepts and ideas (except for the underlying implementation details, which provide a great deal of new constructions and techniques, but are pointless to explain without the necessary background knowledge). This is why those concerns can't really be addressed in a short version.

**Comment by snoeyink** [comment]
Yes, I know that time is short, and you thought the number of pages was limited.  Since it is not, please do add some words to characterize the intended audience and tell them what they can expect to learn.  

I noticed you were in North Carolina from your GitHub, and I'd be happy to talk to you about your experiences with Julia and coding for geometric algebra.  I'd been traveling in the last two weeks, but am around Chapel Hill for the rest of the summer.  If you want to give a practice run of your JuliaCon talk, I could arrange a small audience here in UNC Chapel Hill, Computer Science.

**Comment by chakravala** [comment]
Alright then, I could come by next week sometime, perhaps the math department would be interested in it too? It's only a 10 minute presentation, but I can answer some questions.

**Comment by snoeyink** [comment]
I’m sorry, but I had the shingles vaccine knock me back  for a couple of days this week.  I hope you enjoy JuliaCon.

Jack Snoeyink@cs.unc.edu
Computer Science, UNC Chapel Hill

**Comment by goballooning** [comment]
Personally I feel that this work can be divided into two papers:
- one targeting researchers in GA applications,
- and the other for the audience cares more about the fundamental concepts behind Grassmann.jl and how these concepts are properly handled to fit into Julia.

**Comment by chakravala** [comment]
This issue is being closed for now, although you are welcome to re-open or discuss further!

@snoeyink, I would be interested to give an extended presentation at your department, if desired.

More research papers will be written, but I can't currently provide a schedule for when they finish.

**Comment by waldyrious** [comment]
> although you are welcome to re-open

FYI, only the repo owner or manually added collaborators can reopen issues that have been closed. Not even the issue author can do so. 🤷‍
