### ISSUE TITLE
Difference between every pair of these: S"++++-", V"++++-" and "++++-"

### ISSUE THREAD

**Issue by goballooning** [chakravala/Grassmann.jl#30]
Hi, 

- On notation: 
What is the difference between every pair of the three: `@basis S"++++-"`, `@basis V"++++-"` and `@basis "++++-"`?
I'm a little confused in trying the examples in `README.md`. It seems they all give me the same results.

- On algebra
In `Grassmann.js`, is `V"++++-"` also the conformal model `G^{4,1}` of `R^3`?
(I noticed in the section "Null-basis of the conformal split" that we can declare a space with signature ∞ and ∅, but did not figure out how I can construct a signature such that it is in correspondence with "++++-". 

Thank you,
Hongying

**Comment by chakravala** [comment]
Thanks for your question. For the first example, there is no difference between them. There is a generic constructor `V"..."` which automatically tries to select the correct sub type of the abstract `Manifold` type, while the `S"..."` constructor is specific for the `Signature` instance. When `S"..."` is used it is specific for signatures of `+/-` values, you also get the option of specifying null-basis by using the `@basis S"∅∞+++"` command. Then the origin always must be specified in the first position and the point at infinity is placed right after the origin.

For the second example: No, `V"++++-"` is not the null-basis split for spacetime, you need to use `S"∅∞+++"` for that. These two algebras are isomorphic to each other, but have different basis. Specifically, instead of an extra basis of + and - in `Signature` you have a null-basis. This is described in my paper, but I recommend reading other books/sources to learn more.

Also related to this is https://github.com/chakravala/DirectSum.jl/issues/2 regarding the generic constructors `V"..."`.
