### ISSUE TITLE
More specific Chain constructors?

### ISSUE THREAD

**Issue by eschnett** [chakravala/Grassmann.jl#62]
I notice that certain constructors for `Chain` work when called generically, but not when called with the specific type:
```Julia
julia> Chain{V,1}(1,2)
1v₁ + 2v₂

julia> Chain{V,1,Int}(1,2)
ERROR: MethodError: no method matching Chain{⟨++⟩,1,Int64,253} where 253(::Int64, ::Int64)
```

Similarly:
```Julia
julia> Chain(B.v1)
1v₁ + 0v₂

julia> Chain{Int}(B.v1)
1v₁ + 0v₂
```

but:
```Julia
julia> Chain{V}(B.v1)
ERROR: MethodError: no method matching SubManifold{⟨++⟩,0,0x0000000000000000}(::Simplex{⟨++⟩,0,v,Int64})

julia> Chain{V,1}(B.v1)
ERROR: DimensionMismatch("No precise constructor for StaticArrays.SArray{Tuple{2},SubManifold{⟨++⟩,1,0x0000000000000001},1,2} found. Length of input was 1.")

julia> Chain{V,1,Int}(B.v1)
ERROR: MethodError: Cannot `convert` an object of type SubManifold{⟨++⟩,1,0x0000000000000001} to an object of type StaticArrays.SArray{Tuple{2},Int64,1,2}
```

It would be convenient if one could always call a specific constructor. That is, if a constructor creates a certain type `Chain{V,1,T}`, then I'd prefer if I was always able to call `Chain{V,1,T}`, and not have to use `Chain{V,1}` or `Chain{T}` instead.

This is not urgent.

**Comment by chakravala** [comment]
No, I do not intend on supporting the constructors in that particular way.

The current design is intentional, because each of these different constructors should not overlap.

The error message should help make it clear to new users that these are different construction methods, and that they do not overlap.

EDIT: however, the Chain constructor has been updated in v0.8
