### ISSUE TITLE
abs2 is not type-stable

### ISSUE THREAD

**Issue by eschnett** [chakravala/Grassmann.jl#64]
The result type of `abs2` seems to depend on argument values:

```Julia
julia> @basis 2
(⟨++⟩, v, v₁, v₂, v₁₂)

julia> abs2(MultiVector(v+v1)) |> typeof
MultiVector{⟨++⟩,Int64,4}

julia> abs2(MultiVector(v)) |> typeof
Simplex{⟨++⟩,0,v,Int64}
```

The return type of a function should usually only depend on the argument types.

I am currently not running benchmarks, so this does currently not affect me.

**Comment by chakravala** [comment]
That's not a bug, it's a feature. It performs better this way. To keep it type stable, it would be necessary to output a full `MultiVector` when only a `Simplex` would do. Having a scalar `Simplex` instead of a full valued `MultiVector` is faster for computing `exp` and other essential methods.

This is intentional and will not be changed.
