### ISSUE TITLE
Up- and downarrow convert rational numbers to floating-point numbers

### ISSUE THREAD

**Issue by eschnett** [chakravala/Grassmann.jl#65]
I find that the uparrow and downarrow operators for conformal geometries convert rational numbers to floating-point numbers:
```Julia
julia> using Grassmann

julia> S = Signature(4, 1, 1)
⟨∞∅++⟩

julia> V = SubManifold(S)
⟨∞∅++⟩

julia> B = Λ(S)
DirectSum.Basis{⟨∞∅++⟩,16}(v, v∞, v∅, v₁, v₂, v∞∅, v∞₁, v∞₂, v∅₁, v∅₂, v₁₂, v∞∅₁, v∞∅₂, v∞₁₂, v∅₁₂, v∞∅₁₂)

julia> Chain{V,1}(1//1,2//1,3//1,4//1)
(1//1)v∞ + (2//1)v∅ + (3//1)v₁ + (4//1)v₂

julia> x = Chain{V,1}(1//1,2//1,3//1,4//1)
(1//1)v∞ + (2//1)v∅ + (3//1)v₁ + (4//1)v₂

julia> ↑(x)
-0.0 + 11.5v∞ + 3.0v∅ + 3.0v₁ + 4.0v₂

julia> ↓(x)
0.0 + 1.5v₁ + 2.0v₂
```

The problem is caused by the terms `G.v∞/2` and `inv(G.v∞∅)`, which don't have any type information and thus default to `Float64`. Multiplying the basis vectors by `one(valuetype(\omega))` before the division/inversion solves the problem.

This breaks my code because I like to use rational numbers for testing to avoid round-off errors. I am currently using a corrected copy of these functions that I copied into my code.

**Comment by chakravala** [comment]
Glad you figured out the difference between `S` and `V`, I'm not sure yet how to explain that to people in the documentation, or whether to hide away that detail completely from users.

Please do share your modified versions of the methods here.

**Comment by eschnett** [comment]
```Julia
function Grassmann.:↑(::Val{:fixed}, ω::T) where T<:TensorAlgebra
    V = Manifold(ω)
    !(hasinf(V)||hasorigin(V)) && return ω
    G = Λ(V)
    return if hasinf(V) && hasorigin(V)
        ((G.v∞*(one(valuetype(ω))/2))*ω^2+G.v∅)+ω
    else
        ω2 = ω^2
        iω2 = inv(ω2+1)
        (hasinf(V) ? G.v∞ : G.v∅)*(ω2-1)*iω2 + 2*iω2*ω
    end
end

function Grassmann.:↓(::Val{:fixed}, ω::T) where T<:TensorAlgebra
    V = Manifold(ω)
    !(hasinf(V)||hasorigin(V)) && (return ω)
    G = Λ(V)
    return if hasinf(V) && hasorigin(V)
        inv(one(valuetype(ω))*G.v∞∅)*(G.v∞∅∧ω)/(-ω⋅G.v∞)
    else
        b = hasinf(V) ? G.v∞ : G.v∅
        ((ω∧b)*b)/(1-b⋅ω)
    end
end
```

**Comment by eschnett** [comment]
If `S` and `V` printed differently, then it would have been easier for me to spot the difference. At the moment I have to use a lot of `typeof` to spot the difference.

**Comment by chakravala** [comment]
Alright, you could make that a PR I think, since that wouldn't be a breaking change, or I'll add it myself.

So, there are actually a lot of good reasons why `S` and `V` have to be different entities, which may not be immediately obvious. Since `V` is a `SubManifold` it is an extremely general entity, which can be built on something like `S` (which is a `TensorBundle`); however, a `SubManifold` can also recursively be constructed from another `SubManifold` or from a `ChainBundle` too. In this case, the example is `S` being a `Signature<:TensorBundle`, but there are other `TensorBundle` types too. Currently, the printing will remain the same, but maybe that could change (if it's an elegant change).
