### ISSUE TITLE
Confusion about mixed grade contraction

### ISSUE THREAD

**Issue by hzgzh** [chakravala/Grassmann.jl#88]
I am learning the geometric algebra,try to compute mixed product,I found the result is different to the book result.
`julia> using Grassmann

julia> basis"3"
(⟨×××⟩, v, v₁, v₂, v₃, v₁₂, v₁₃, v₂₃, v₁₂₃)

julia> using LinearAlgebra

julia> v1⋅(v1*v2)#should be v2,a vector inner prodcut a bivector is different from the book
0v

julia> v1∧(v1*v2)
0v
`

**Comment by chakravala** [comment]
That is not a bug but by design, since the `\cdot` operation is defined as the `∨⋆` operation:
```Julia
julia> basis"3"
(⟨×××⟩, v, v₁, v₂, v₃, v₁₂, v₁₃, v₂₃, v₁₂₃)

julia> v1⋅v12 == v1∨⋆v12
true

julia> v12⋅v1 == v12∨⋆v1
true

julia> v1⋅v12, v12⋅v1
(0v, 1v₂)
```

**Comment by hzgzh** [comment]
how to get right answer for v1\cdot v12

**Comment by chakravala** [comment]
The right answer is 0. Probably, you are reading some book which doesn't use the original Grassmann convention for interior products, as my package does. Grassmann.jl is based on the OG (original Grassmann) product.

However, if you wish you can use the left contraction variant using `<` instead of `>` or `/cdot` (which are the right contraction).
```julia
julia> v1<v12
1v₂
```
Note that the left contraction in `Grassmann` is still different from what some other authors use, such as Leo Dorst, as detailed in my documentation and in this tweet I made: https://twitter.com/dreamscatter/status/1384242523577610251

I don't currently have time to fully teach and explain all the nuances of `Grassmann` as I've already explained this many times elsewhere, but I'd be happy to teach you more about these nuances if you sponsor me on github, liberapay, patreon, etc.

**Comment by hzgzh** [comment]
Thanks
